config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  Rails.application.routes.draw do
    resources :topics
    get "topics", to: "topics#index"
    get "topics/:id", to: "topics#show"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :topic_prerequisites, class_name: "TopicPrerequisite", foreign_key: "source_topic_id"
    has_many :prerequisites, through: :topic_prerequisites, source: :preq_topic

    has_many :topic_nextsteps, class_name: "TopicPrerequisite", foreign_key: "preq_topic_id"
    has_many :nextsteps, through: :topic_nextsteps, source: :source_topic
end

app/models/topic_prerequisite.rb
class TopicPrerequisite < ApplicationRecord
  belongs_to :source_topic, class_name: "Topic"
  belongs_to :preq_topic, class_name: "Topic"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def require_trailing_slash
        if !request.original_fullpath.end_with?('/')
            redirect_to request.original_fullpath + '/'
        end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    require_trailing_slash
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "LearnGraph" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/index.html.erb
<% content_for :title, "Browse Topics" %>
<%= stylesheet_link_tag 'contentpage.css' %>
<%= stylesheet_link_tag 'topics/index.css' %>

<div id="page-content">
    <div id="content-header" class="content-tile">
        <h1>Topics</h1>
    </div>

    <div id="content" class="content-tile">
        <h2 class="tile-header">Browse Topics</h2>
        <ul>
            The following topics are currently available:
            <% @topics.each do |topic| %>
                <li>
                    <a href = "./<%= topic.id %>">
                        <%= topic.title %>
                    </a>
                </li>
            <% end %>
        </ul>
        <div id="container"></div>
    </div>

    <div id="content-about" class="content-tile">
        <h2 class="tile-header">About</h2>
        <p>
            This is my Honors 4990 Project.
        </p>
    </div>
</div>

<script type="text/json" id="node-data">
    <%= @topics.map { |topic| 
        {
            id: topic.id,
            title: topic.title,
        }
    }.to_json.html_safe %>
</script>
<script type="text/json" id="link-data">
    <%= @topics.map { |topic|
        topic.prerequisites.map { |prereq|
            {
                source: topic.id,
                target: prereq.id,
            }
        }
    }.flatten.to_json.html_safe %>
</script>
<script type="module">
    const width = 800;
    const height = 600;
    const radius = 60;

    import * as d3 from "https://cdn.jsdelivr.net/npm/d3@7/+esm";

    const nodes = JSON.parse(document.getElementById("node-data").textContent);
    const links = JSON.parse(document.getElementById("link-data").textContent);

    function textWrap(text, width) {
        text.each(function() {
            let text = d3.select(this);
            let words = text.text().split(/\s+/);
            let base = text.text(null);
            let line = base.append("tspan").text(words.shift());
            while (words.length > 0) {
                let prevText = line.text();
                let word = words.shift();
                line.text(prevText + " " + word)
                    .attr("text-anchor", "middle")
                    .attr("x", width / 2);
                if (line.node().getComputedTextLength() > width * .9) {
                    line.text(prevText);
                    line = base.append("tspan")
                        .text(word)
                        .attr("dy", "1em")
                        .attr("text-anchor", "middle")
                        .attr("x", width / 2);
                }
            }

            text.attr("y", -line.node().getBBox().height / 2);
        })
    }

    function getNodeById(id) {
        return nodes.find(node => node.id === id);
    }

    const svg = d3.create("svg")
        .attr("width", width)
        .attr("height", height);

    const link = svg.selectAll(".link")
        .data(links)
        .join("line")
        .attr("stroke", "#000000")
        .attr("stroke-width", 2);

    const node = svg.selectAll(".node")
        .data(nodes).enter().append("g");

    node.attr("id", d => d.id);

    node.append("circle")
        .attr("r", radius)
        .attr("cx", radius)
        .attr("fill", "#69b3a2");

    let text = node.append("text")
        .text(d => d.title)
        .attr("fill", "#000000")
        .attr("x", radius)
    setTimeout(() => {
        text.call(textWrap, radius * 2);
    }, 0);

    node.append("title")
        .text(d => d.title);

    const simulation = d3.forceSimulation(nodes)
        .force("charge", d3.forceManyBody().strength(-100))
        .force("center", d3.forceCenter(width / 2, height / 2))
        .force("collide", d3.forceCollide(50));
        
    simulation.on("tick", () => {
        node.attr("transform", d => `translate(${d.x},${d.y})`);
        link
            .attr("x1", d => getNodeById(d.source).x + radius)
            .attr("y1", d => getNodeById(d.source).y)
            .attr("x2", d => getNodeById(d.target).x + radius)
            .attr("y2", d => getNodeById(d.target).y);
    });
    
    node.on("mouseover", function() {
        d3.select(this).select("circle").attr("r", radius * 1.75);
    });
    node.on("mouseout", function() {
        d3.select(this).select("circle").attr("r", radius);
    });
    node.on("click", function(d) {
        let id = d3.select(this).node().id;
        window.location.href = `./${id}`;
    });

    document.getElementById("container").appendChild(svg.node());
</script>

app/views/topics/show.html.erb
<% require 'code_html_renderer' %>

<% content_for :title, @topic.title %>
<%= stylesheet_link_tag 'contentpage.css' %>
<%= stylesheet_link_tag 'topics/show.css' %>
<style><%= Pygments.css('.highlight') %></style>

<div id="page-content">
    <div id="content-header" class="content-tile">
        <h1 id="content-title"><%= @topic.title %></h2>
        <a href="/topics" id="backnav">Back to Topics List</a>
    </div>
    <div id="content-prerequisites" class="content-tile">
        <h2 class="tile-header">Prerequisites</h2>
        <% if @topic.prerequisites.empty? %>
            <p>This topic has no prerequisites.</p>
        <% end %>
        <ul>
            <% @topic.prerequisites.each do |prereq| %>
                <li><%= link_to(prereq.title, topic_path(prereq)) %></li>
            <% end %>
        </ul>
    </div>
    <div id="content" class="content-tile">
        <h2 class="tile-header">Lesson</h2>
        <% renderer = CodeHtmlRenderer.new(render_options = {
            escape_html: true,
            prettify: true,
        }) %>
        <%= raw Redcarpet::Markdown.new(renderer, extensions = {
            fenced_code_blocks: true,
            tables: true,
        }).render(@topic.content) %>
    </div>
    <div id="content-nextsteps" class="content-tile">
        <h2 class="tile-header">Next Steps</h2>
        <% if @topic.nextsteps.empty? %>
            <p>This topic has no next steps. Congratulations on finishing the current path!</p>
        <% end %>
        <ul>    
            <% @topic.nextsteps.each do |nextstep| %>
                <li><%= link_to(nextstep.title, topic_path(nextstep)) %></li>
            <% end %>
        </ul>
    </div>
</div>